-- CREATE DATABASE
CREATE DATABASE bookstore;

-- SWITCH TO THE DATABASE
USE bookstore;

-- CREATE TABLES
CREATE TABLE BOOKS(
  Book_ID INT PRIMARY KEY,
  Title	VARCHAR(100),
  Author VARCHAR(100),
  Genre	VARCHAR(100),
  Published_Year INT,
  Price	NUMERIC(10,2),
  Stock	INT
);

CREATE TABLE CUSTOMERS(
  Customer_ID INT PRIMARY KEY,
  Name VARCHAR(100),
  Email VARCHAR(100),
  Phone VARCHAR(15),
  City VARCHAR(100),
  Country VARCHAR(100)
);

CREATE TABLE ORDERS(
  Order_ID INT PRIMARY KEY,
  Customer_ID INT,
  Book_ID INT,
  Order_Date DATE,
  Quantity INT,
  Total_Amount NUMERIC(10,2),
  FOREIGN KEY(Book_ID)REFERENCES BOOKS(Book_ID),
  FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(Customer_ID)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);

-- IMPORT DATA INTO BOOKS TABLE
SELECT*FROM BOOKS AS b;

-- IMPORT DATA INTO CUSTOMERS TABLE
SELECT*FROM CUSTOMERS as c;

-- IMPORT DATA INTO ORDERS TABLE
SELECT*FROM ORDERS as o;

DROP DATABASE IF EXISTS bookstore;
DROP TABLE IF EXISTS ORDERS;
SELECT COUNT(DISTINCT Order_ID);
SELECT COUNT(*)FROM ORDERS;
DESC ORDERS;

select Customer_ID
FROM CUSTOMERS
ORDER BY Customer_ID;

-- 1
-- RETRIEVE THE COUNTS OF BOOKS IN THE "Fiction" GENRE:
SELECT COUNT(*)FROM BOOKS
WHERE GENRE="FICTION";

-- 2
-- RETRIEVE ALL BOOKS IN THE "Fiction" GENRE:
SELECT*FROM BOOKS 
WHERE GENRE="FICTION"; 

-- 3
-- FIND BOOKS PUBLISHED AFTER THE YAER 1950:
SELECT*FROM BOOKS
WHERE Published_year>=1950;

-- 4
-- LIST ALL CUSTOMERS FROM THE "Canada":
SELECT*FROM CUSTOMERS
WHERE Country="CANADA";

-- 5
-- SHOW ORDERS PLACED IN NOVEMBER 2023:
SELECT * FROM ORDERS 
WHERE ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';

-- 6
-- RETRIEVE THE TOTAL STOCK OF BOOKS AVAILABLE:
SELECT SUM(Stock)as Total_stock
from BOOKS;

-- 7
-- FIND THE DETAILS OF MOST EXPENSIVE BOOKS:
SELECT * FROM BOOKS
ORDER BY Price DESC limit 1;

-- 8
-- SHOW CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY OF A BOOK:
SELECT*FROM ORDERS
WHERE Quantity>1;

-- 9
-- RETRIEVE ALL ORDERS WHERE THE TOTAL AMOUNT EXCEEDS $20:
SELECT*FROM ORDERS
WHERE Total_Amount>20; 

-- 10
-- LIST ALL GENRES AVAILABLE IN THE BOOKS TABLE:
SELECT DISTINCT Genre FROM BOOKS;

-- 11
-- FIND THE BOOK WITH LOWEST STOCK:
SELECT * FROM BOOKS
ORDER BY Stock ASC LIMIT 1 ;

-- 12
-- CALCULATE THE TOTAL REVENUE GENERATED FROM ALL ORDERS:
SELECT SUM(Total_Amount) as REVENUE FROM ORDERS;

-- 12
-- RETRIEVE  THE TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE:
SELECT Genre,sum(Quantity) FROM ORDERS
join BOOKS
ON ORDERS.Book_ID = BOOKS.Book_ID
GROUP by genre;

-- 13
-- FIND THE AVERAGE PRICE OF  BOOKS IN THE "FANTASY" GENRE:
SELECT Genre,avg(Price) from BOOKS
group by Genre
HAVING Genre="Fantasy";

-- 14
-- LIST OF CUSTOMERS WHO HAVE PLACED AT LEAST TWO ORDERS:
SELECT Customer_ID, count(Order_ID) FROM  ORDERS
group by Customer_ID
HAVING count(Order_ID)>=2;

-- 15
-- FIND THE MOST FREQUENTLY ORDERED BOOK:
SELECT o.Book_ID,b.title,count(o.Order_ID)from ORDERS o
join BOOKS b 
on o.Book_ID=b.Book_ID
group by o.Book_ID
order by count(Order_ID) desc limit 1;

-- 16
-- SHOW THE TOP3 MOST EXPENSIVE BOOKS OF'FANTASY'GENRE:
SELECT * from BOOKS
WHERE Genre="Fantasy"
order by price desc limit 3;

-- 17
-- RETRIEVE THE TOTAL QUANTITY OF BOOKS SOLD BY EACH AUTHOR:
SELECT b.Author,sum(ORDERS.Quantity) FROM ORDERS
JOIN BOOKS b 
ON b.Book_ID=ORDERS.Book_ID
group by b.Author;

SELECT count( DISTINCT Author) from BOOKS; 

-- 18
-- LIST THE CITIES WHERE CUSTOMERS WHO SPENT OVER $30 ARE LOCATED:
-- CITY
SELECT distinct City FROM CUSTOMERS
join ORDERS
on ORDERS.Customer_ID=CUSTOMERS.Customer_ID
where ORDERS.Total_amount>30;

-- CITY WITH TOTAL_AMOUNT
SELECT distinct CUSTOMERS.City,Total_Amount FROM ORDERS
join CUSTOMERS
on ORDERS.Customer_ID=CUSTOMERS.Customer_ID
where ORDERS.Total_amount>30;

-- 19
-- FIND THE CUSTOMERS WHO SPENT THE MOST ON ORDERS:
SELECT CUSTOMERS.Customer_ID,CUSTOMERS.Name,sum(ORDERS.Total_Amount)from ORDERS 
join CUSTOMERS
on ORDERS.Customer_ID=CUSTOMERS.Customer_ID
group by CUSTOMERS.Customer_ID,CUSTOMERS.Name
order by SUM(ORDERS.Total_Amount) desc limit 1;


